### ISSUE TITLE
Add a search bar with search functionality.

### ISSUE THREAD

**Issue by awais-124** [awais-124/valorant-api#2]
##  Feature Request
> Add a search bar with backend functionality.

> What needs to be done.
- Add a search bar on top of page.
- Add it below navbar.
- Make it responsive
- Add functionality so that users can search bundles and agents.
- Sort items based on search keystroke.
- Sort on every key stroke.
- Feel free to style search bar.

> Contributing
- Fork the repo.
- Create a new branch with name as 'ISSUE-(Issue Number)'.
- Create a pull request once done.

**Comment by LaibaKhalil61** [comment]
I'd like to do it

**Comment by awais-124** [comment]
> I'd like to do it

Yes plz.

**Comment by vincyy24** [comment]
> * Sort items based on search keystroke

Hi, do you mean `Sort` or `Filter` on every keystroke?

**Comment by awais-124** [comment]
> > * Sort items based on search keystroke
> 
> Hi, do you mean `Sort` or `Filter` on every keystroke?

Yes, its filter in fact. Thank You!

**Comment by LaibaKhalil61** [comment]
Is the search bar is to be added only on Agents and Bundles page? As you have mentioned "Add functionality so that users can search bundles and agents."

**Comment by awais-124** [comment]
> Is the search bar is to be added only on Agents and Bundles page? As you have mentioned "Add functionality so that users can search bundles and agents."

Yes only on them.

**Comment by vincyy24** [comment]
Hey @awais-124, I tried to complete the same issue, can you take a look? [Here's the branch](https://github.com/vincyy24/valorant-api/tree/feature/search-bar)

**Comment by awais-124** [comment]
> Hey @awais-124, I tried to complete the same issue, can you take a look? [Here's the branch](https://github.com/vincyy24/valorant-api/tree/feature/search-bar)

Good Job!. Just need to make few changes.
- Move the search-bar to right side of web page. 
- Align it with Main Heading. Keep them both at same level row-wise.
- Currently you are searching if query is included in agents'/bundles' name, change it startsWith. 
- Use `.startsWith() method`.
```js
const filterBySearch = (data, key) =>
		data.filter((item) =>
			item[key].toUpperCase().includes(searchValue.toUpperCase()) 
		);
```

**Comment by vincyy24** [comment]
> > Hey @awais-124, I tried to complete the same issue, can you take a look? [Here's the branch](https://github.com/vincyy24/valorant-api/tree/feature/search-bar)
> 
> Good Job!. Just need to make few changes.
> 
> * Move the search-bar to right side of web page.
> * Align it with Main Heading. Keep them both at same level row-wise.
> * Currently you are searching if query is included in agents'/bundles' name, change it startsWith.
> * Use `.startsWith() method`.
> 
> ```js
> const filterBySearch = (data, key) =>
> 		data.filter((item) =>
> 			item[key].toUpperCase().includes(searchValue.toUpperCase()) 
> 		);
> ```

Just committed the changes, should I create a pull request now or any more changes?
I tried to keep the heading and the search bar at same level, but at smaller screens it could break the design so I went with column flow for smaller widths..

**Comment by awais-124** [comment]
> > > Hey @awais-124, I tried to complete the same issue, can you take a look? [Here's the branch](https://github.com/vincyy24/valorant-api/tree/feature/search-bar)
> > 
> > 
> > Good Job!. Just need to make few changes.
> > 
> > * Move the search-bar to right side of web page.
> > * Align it with Main Heading. Keep them both at same level row-wise.
> > * Currently you are searching if query is included in agents'/bundles' name, change it startsWith.
> > * Use `.startsWith() method`.
> > 
> > ```js
> > const filterBySearch = (data, key) =>
> > 		data.filter((item) =>
> > 			item[key].toUpperCase().includes(searchValue.toUpperCase()) 
> > 		);
> > ```
> 
> Just committed the changes, should I create a pull request now or any more changes? I tried to keep the heading and the search bar at same level, but at smaller screens it could break the design so I went with column flow for smaller widths..

- Plz stick with the heading's old position. Keep it centered.
- For smaller devices, you went well, column flow would be nicer.
- Just change this and create pull request. 
Thank You
